version: '3.9'

services:
  backend:
    build:
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      # -users  
    networks:
      - monolith

  db:
    imaage: mysql:8
    restart: always
    enviroment:
      MYSQL_DATABASE: chantos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306 
    networks:
      - monolith
